//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.06.26 at 08:48:51 AM EDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "urn:ihe:iti:xds-b:2007", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ihe.iti.xds_b._2007;
